### PR TITLE
Quiet option

### PR DESCRIPTION
**Pull request by fabiosantoscode**
This came up while @xicombd was writing something using minigun.

It is unshibelike to not say anything, but this PR adds the `--quiet`/`-q` option to the command line, which can also be passed through javascript.

Although it might not be so useful on the command line, scripts using minigun as a library will want to stop it from writing to stdout.

### CODE REVIEW

**Comment by xicombd** [comment]
:+1:

**Comment by hassy** [comment]
doge

Thanks! :+1: This is a needed option.

Changes that need to be made before merging:
- there is no need to pass quiet to core (it should not output anything to stdout/stderr)
- `dino` does not need a quiet option :)

**Comment by xicombd** [comment]
Hey @hassy! Where are we actually passing the quiet option to core?

**Comment by fabiosantoscode** [comment]
@xicombd was kind enough to PR into my PR

**Comment by hassy** [comment]
Thanks guys! :)

shibe

**Pull request merged**
